name: Dependabot PR merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create table from dependabot metadata
        id: meta-table
        uses: parkerbxyz/json-to-markdown-table@v1.1.2
        with:
          json: ${{ steps.metadata.outputs.updated-dependencies-json }}
      - name: Comment the table in PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.meta-table.outputs.table }}
          pr-number: ${{ github.event.pull_request.number }}
      - name: Assign me as assignee
        if: steps.metadata.outputs.package-ecosystem == 'npm' && steps.metadata.outputs.update-type == 'version-update:semver-major'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.addAssignees({
                assignees: ['gnpaone'],
                issue_number: `${{ github.event.pull_request.number }}`,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ !(steps.metadata.outputs.package-ecosystem == 'npm' && steps.metadata.outputs.update-type == 'version-update:semver-major') }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
