name: Dependabot PR merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create table from dependabot metadata
        id: meta-table
        uses: parkerbxyz/json-to-markdown-table@v1.1.2
        with:
          json: ${{ steps.metadata.outputs.updated-dependencies-json }}
      - name: Comment the table in PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.meta-table.outputs.table }}
          pr-number: ${{ github.event.pull_request.number }}
      - name: Checkout PR branch
        if: steps.metadata.outputs.package-ecosystem == 'npm_and_yarn'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install node
        if: steps.metadata.outputs.package-ecosystem == 'npm_and_yarn'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: Build package
        if: steps.metadata.outputs.package-ecosystem == 'npm_and_yarn'
        shell: bash
        working-directory: npm/rust-just
        continue-on-error: true
        id: build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Comment the build error message
        if: steps.metadata.outputs.package-ecosystem == 'npm_and_yarn' && steps.build.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            @gnpaone Build failed!
            ```bash
            ${{ steps.build.outputs.stderr }}
            ```
          pr-number: ${{ github.event.pull_request.number }}
      - name: Assign me as assignee
        if: steps.metadata.outputs.package-ecosystem == 'npm_and_yarn' && (steps.metadata.outputs.update-type == 'version-update:semver-major' || steps.build.outcome == 'failure')
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.addAssignees({
                assignees: ['gnpaone'],
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ !(steps.metadata.outputs.package-ecosystem == 'npm_and_yarn' && (steps.metadata.outputs.update-type == 'version-update:semver-major' || steps.build.outcome == 'failure')) }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
